import type { Metadata } from 'next';
import { Baloo_Thambi_2 } from 'next/font/google';
import './globals.css';
import ConvexClientProvider from './ConvexClientProvider';
import Header from './header';

const font = Baloo_Thambi_2({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={font.className}>
				<ConvexClientProvider>
					<Header />
					{children}
				</ConvexClientProvider>
			</body>
		</html>
	);
}
